[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.12.1"
perseus = "0.3.2"
perseus-size-opt = "0.1.7"
sycamore = "0.7"
